version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "solana*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
