allow-branch = ["main", "master"]
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
tag-message = "{{crate_name}}-v{{version}}"
tag-name = "{{crate_name}}-v{{version}}"
