[package]
name = "nitrogen-circle-message-transmitter-v2-encoder"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
bon = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }


[lints]
workspace = true
